import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { BottomTabNavigationProp } from '@react-navigation/bottom-tabs';
import { Supplier } from './inventory';

export type MainTabParamList = {
  Home: undefined;
  Inventory: undefined;
  AllWarehouses: undefined;
  Bookings: undefined;
  Scan: undefined;
  Profile: undefined;
};

export type RootStackParamList = {
  Onboarding: undefined;
  Login: undefined;
  Signup: undefined;
  ForgotPassword: undefined;
  MainTabs: undefined;
  AllProducts: undefined;
  Product: { product: any };
  AddProduct: { product?: any };
  AllTransfers: undefined;
  LowStockInventory: undefined;
  Warehouse: undefined;
  WarehouseReports: undefined;
  AllWarehouses: undefined;
  BinManagement: undefined;
  SuppliersScreen: undefined;
  SupplierDetailsScreen: { supplierId: string };
  SupplierFormScreen: { supplier?: Supplier };
  ProductSuppliersScreen: undefined;
  ProductSupplierFormScreen: { productSupplier?: any };
  PurchaseOrdersScreen: undefined;
  PurchaseOrderDetailsScreen: { orderId: string };
  PurchaseOrderFormScreen: { order?: any; isEditing: boolean };
  InventoryReportsScreen: undefined;
  PriceLists: undefined;
  PriceListDetailsScreen: { priceListId: string };
  PriceListProductsScreen: { priceListId: string };
  EditPriceListScreen: { priceList?: any; isEditing: boolean };
  BatchesScreen: undefined;
  BatchDetailsScreen: { batchId: string };
  EditBatchScreen: { batch?: any; isEditing: boolean };
  ProfileEdit: undefined;
};

export type LoginScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'Login'>;
export type SignupScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'Signup'>;
export type OnboardingScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'Onboarding'>;
export type HomeScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'MainTabs' | 'BatchesScreen' | 'PriceLists'>;
export type InventoryScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'MainTabs' | 'AllProducts' | 'Warehouse' | 'SuppliersScreen' | 'PurchaseOrdersScreen' | 'InventoryReportsScreen' | 'AllWarehouses' | 'BinManagement' | 'LowStockInventory' | 'AllTransfers' | 'WarehouseReports' | 'PriceLists'>;
export type AllProductsScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'AllProducts' | 'Product' | 'AddProduct'>;
export type AllTransfersScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'AllTransfers'>;
export type LowStockInventoryScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'LowStockInventory'>;
export type SuppliersScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'SuppliersScreen' | 'SupplierDetailsScreen' | 'SupplierFormScreen' | 'ProductSuppliersScreen' | 'ProductSupplierFormScreen' | 'PurchaseOrdersScreen' | 'PurchaseOrderDetailsScreen' | 'PurchaseOrderFormScreen'>;
export type SupplierDetailsScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'SupplierDetailsScreen' | 'SupplierFormScreen'>;
export type SupplierFormScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'SupplierFormScreen' | 'SuppliersScreen'>;
export type ProductSuppliersScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'ProductSuppliersScreen' | 'ProductSupplierFormScreen'>;
export type ProductSupplierFormScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'ProductSupplierFormScreen' | 'ProductSuppliersScreen'>;
export type PurchaseOrdersScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'PurchaseOrdersScreen' | 'PurchaseOrderDetailsScreen' | 'PurchaseOrderFormScreen'>;
export type PurchaseOrderDetailsScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'PurchaseOrderDetailsScreen' | 'PurchaseOrderFormScreen'>;
export type PurchaseOrderFormScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'PurchaseOrderFormScreen' | 'PurchaseOrdersScreen'>;